version: '3'

services:
  app:
    build: ./
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - ./:/frontend
    stdin_open: true
    tty: true
    networks:
      - inbenta-test-network
networks:
  inbenta-test-network:
    driver: bridge